Repository GEWIS/gewisdb, pull requests merged in 2023-05, with the labels that each got.

#284 Implement API principal management
  .gitattributes
  Makefile
  module/Application/config/module.config.php
  module/Application/language/en.po
  module/Application/language/gewisdb.pot
  module/Application/language/nl.po
  module/Application/src/View/Helper/BootstrapElementError.php
  module/Application/src/View/HelperTrait.php
  module/Application/view/layout/layout.phtml
  module/Database/src/Controller/ApiController.php
  module/Database/src/Service/Api.php
  module/Database/view/database/member/subscribe.phtml
  module/Database/view/database/settings/index.phtml
  module/User/config/module.config.php
  module/User/src/Controller/ApiSettingsController.php
  module/User/src/Controller/Factory/ApiSettingsControllerFactory.php
  module/User/src/Controller/SettingsController.php
  module/User/src/Controller/UserController.php
  module/User/src/Form/ApiPrincipal.php
  module/User/src/Listener/AuthenticationListener.php
  module/User/src/Model/ApiPrincipal.php
  module/User/src/Model/Enums/ApiPermissions.php
  module/User/src/Module.php
  module/User/src/Service/ApiAuthenticationService.php
  module/User/src/Service/ApiPrincipalService.php
  module/User/src/Service/Factory/ApiPrincipalServiceFactory.php
  module/User/src/Service/Factory/UserServiceFactory.php
  module/User/src/Service/UserService.php
  module/User/view/user/api-settings/create-principal.phtml
  module/User/view/user/api-settings/edit-principal.phtml
  module/User/view/user/api-settings/list-principals.phtml
  module/User/view/user/settings/create-user.phtml
  module/User/view/user/settings/edit-user.phtml
  module/User/view/user/settings/list-user.phtml
  module/User/view/user/user/index.phtml
  openapi.yaml
  phpcs.xml.dist
  psalm.xml
Labels: For: Backend

#290 Also require sorting of .pot files
  .dockerignore
  module/Application/language/gewisdb.pot
  module/Application/language/nl.po
  translate-helper
Labels: Priority: Low

#287 Updated dependencies
  composer.lock
  composer.phar
Labels: For: Backend, Module: Application, Type: Dependencies
